name: workflow-1
run-name: ${{ github.actor }} is learning GitHub Actions
on: workflow_dispatch
jobs:
  job1:
    runs-on: windows-2022
    steps:
      # - run: wmic os get version
      - run: ls C:\Android\android-sdk\cmdline-tools
      - run: ls C:\Android\android-sdk
      - run: echo $env:ANDROID_HOME
      - run: ls $env:JAVA_HOME_11_X64
      - run: echo $env:JAVA_HOME_11_X64
