name: workflow-1
run-name: ${{ github.actor }} is learning GitHub Actions
on: workflow_dispatch
jobs:
  job1:
    runs-on: windows-2022
    steps:
      # - run: ls $env:JAVA_HOME_11_X64
      # - run: echo $env:JAVA_HOME_11_X64
      # - run: ls C:\Android\android-sdk\cmdline-tools
      # - run: ls C:\Android\android-sdk
      # - run: echo $env:ANDROID_HOME
      - run: systeminfo
      - name: 同意安卓许可
        uses: SimonMarquis/android-accept-licenses@v1
      - name: 查看安装的软件包
        run: |
          & $env:ANDROID_HOME\cmdline-tools\latest\bin\sdkmanager.bat --list_installed
      - name: 安卓sdk软件包安装
        run: |
          & $env:ANDROID_HOME\cmdline-tools\latest\bin\sdkmanager.bat "ndk;19.0.5232133"
      - name: 查看安装的软件包
        run: |
          & $env:ANDROID_HOME\cmdline-tools\latest\bin\sdkmanager.bat --list_installed
      - run: |
          ls C:\Android\android-sdk
          ls C:\Android\android-sdk\ndk
          
